### ISSUE TITLE
Copying checklists in Notes reverts back to plain text

### ISSUE THREAD

**Issue by nehayward** [rknightuk/TrackerZapper#1]
I noticed that this disables copy and pasting checklist items in Notes app. Is it possible to disable this per app?

**Comment by rknightuk** [comment]
In what specific scenario is this happening for you? I just tried it when copying a general checklist list of items and it works for me.

**Comment by nehayward** [comment]
Oh interesting. I'll try and upload a video. Essentially when I copy 

O item

->

'- [ ] item'

It gets converted to plaintext.

**Comment by rknightuk** [comment]
Yep I see the issue now, I'll look into it.

**Comment by rknightuk** [comment]
I briefly looked into this last night and wasn't able to see a way to identify that it's actually a Notes checklist being copied. I will look into this more and see if there's way to work it out.

**Comment by rknightuk** [comment]
This is fixed in version 1.2.1 https://github.com/rknightuk/TrackerZapper/releases/tag/1.2.1
