### ISSUE TITLE
“TrackerZapper.app” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by x4m3** [rknightuk/TrackerZapper#10]
Hi, just downloaded the app from releases, moved it to my Applications folder and tried to open it.

This is what i got: 
<img width="375" alt="image" src="https://user-images.githubusercontent.com/8809909/134207586-70d2e5c4-81e3-47a5-afae-148abe7063cf.png">

I'm on macos big sur 11.5.2 on a macbook air m1 (if that matters).

How can this be resolved? thank you!

**Comment by sogen** [comment]
Use Cmd-Open (or do a mouse **Right** click), then select Open

**Comment by x4m3** [comment]
@sogen i did that, but got the same error message

and after updating to macos 11.6 the app opened just fine. don't know why but it works now.
