### ISSUE TITLE
Add ```s``` (Twitter)

### ISSUE THREAD

**Issue by brandongalbraith** [rknightuk/TrackerZapper#13]
[Twitter adds an "s" parameter to some URLs for tracking purposes](https://twitter.com/mattnavarra/status/1044147538922803201?lang=en): 

![image](https://user-images.githubusercontent.com/350893/137015261-0555c8d2-8e9c-4668-bb31-bfa9de18ffee.png)

Is this too generic of a parameter to add to TrackerZapper? If not, I am happy to submit a PR to add this to the list of URL parameters to sanitize.

Thank you!

**Comment by rknightuk** [comment]
I deliberately left this one off because a lot of sites use this as the search parameter (I have no idea what Twitter is using it for to be honest).
