### ISSUE TITLE
Menu bar icon arbitrarily disappears (but app is still working)

### ISSUE THREAD

**Issue by ShredderWalnut** [rknightuk/TrackerZapper#17]
Hello,

I noticed that TrackerZapper’s menu bar icon would sometimes disappear, but unfortunately I was not able to recognize any discernible pattern of its disappearance. The app is still working during the icon’s disappearance.

Here are some potentially relevant details about my setup:

- Hardware: MacBook Pro 13 inch (2018)
- OS: macOS Monterey 12.1(21C52)
- TrackerZapper version: 1.1.1 (lastest as of writing)

**Comment by rknightuk** [comment]
This might be fixed with [this PR](https://github.com/rknightuk/TrackerZapper/pull/16) which is in version 1.2.1 https://github.com/rknightuk/TrackerZapper/releases/tag/1.2.1
